
const currentPage = document.body.dataset.page || window.location.pathname.split('/').pop() || 'index.html';
const header = `<header class="site-header"><div class="nav-wrap"><a class="logo" href="index.html" aria-label="iPublisho home"><img src="images/ipublisho-logo.svg" alt="iPublisho"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav class="site-nav" id="site-nav" aria-label="Main navigation"><a href="index.html" data-page="index.html">Home</a><a href="author.html" data-page="author.html">About us</a><a href="books-publications.html" data-page="books-publications.html">Books</a><a href="journal.html" data-page="journal.html">Featured journal</a><a href="contact.html" data-page="contact.html" class="nav-cta">Get in touch</a></nav></div></header>`;
const footer = `<footer class="site-footer"><div class="shell"><div class="footer-top"><div><a href="index.html"><img class="footer-logo" src="images/ipublisho-logo.svg" alt="iPublisho"></a><p class="footer-intro">Thoughtful books for curious minds, growing families, and the stories we carry with us.</p></div><div class="footer-links"><div class="footer-column"><strong>Explore</strong><a href="index.html">Home</a><a href="author.html">About us</a><a href="books-publications.html">Books</a><a href="journal.html">Featured journal</a><a href="contact.html">Contact</a></div><div class="footer-column"><strong>Read</strong><a href="privacy-policy.html">Privacy policy</a><a href="legal-disclaimer.html">Legal disclaimer</a><a href="data-deletion.html">Data deletion</a></div><div class="footer-column"><strong>Say hello</strong><a href="mailto:info@ipublisho.com">info@ipublisho.com</a><div class="socials"><a href="https://www.facebook.com/ipublisho/" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 1.9-5 5v3H6v4h3v8h4v-8h3.5l.5-4H13V9c0-.7.3-1 1-1Z" fill="currentColor" stroke="none"/></svg></a><a href="https://x.com/ipublisho/" aria-label="X"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4l14 16M19 4L5 20"/></svg></a><a href="https://www.instagram.com/ipublisho/" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a><a href="https://www.pinterest.com/ipublisho/" aria-label="Pinterest"><svg class="social-pinterest" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a7.7 7.7 0 0 0-2.8 14.9c-.1-1.3 0-2.8.3-4l1-4.1s-.3-.7-.3-1.7c0-1.6.9-2.8 2.1-2.8 1 0 1.5.7 1.5 1.6 0 1-.6 2.4-.9 3.7-.3 1.1.5 2 1.6 2 1.9 0 3.2-2 3.2-4.8 0-2.5-1.8-4.3-4.5-4.3-3.1 0-5 2.3-5 4.8 0 .9.3 1.8.8 2.3.1.1.1.2.1.4l-.3 1.1c-.1.4-.4.5-.7.3-1.3-.6-2-2.4-2-3.9 0-3.2 2.3-6.2 6.7-6.2 3.5 0 6.2 2.5 6.2 5.8 0 3.5-2.2 6.3-5.3 6.3-1 0-2-.5-2.3-1.1l-.6 2.4c-.2.9-.8 2-1.2 2.7.9.3 1.8.5 2.8.5a7.7 7.7 0 1 0 0-15.4Z"/></svg></a></div></div></div></div><div class="footer-bottom"><span>&copy; ${new Date().getFullYear()} iPublisho. All rights reserved.</span><span>Made for curious minds.</span></div></div></footer>`;
document.querySelector('[data-site-header]').innerHTML = header;
document.querySelector('[data-site-footer]').innerHTML = footer;
document.querySelectorAll('.site-nav a[data-page]').forEach((link) => { if (link.dataset.page === currentPage) link.setAttribute('aria-current', 'page'); });
const menuToggle = document.querySelector('.menu-toggle');
const siteNav = document.querySelector('.site-nav');
menuToggle.addEventListener('click', () => { const isOpen = siteNav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(isOpen)); });
